---
required_pkgs:
  - "{{ ( (ansible_distribution_major_version | int) < 8) | ternary('libselinux-python','python3-libselinux') }}"
  - device-mapper-libs
  - nss
  - conntrack
  - ntpdate
  - chrony

container_os_required_pkgs:
  - lvm2
  - tcpdump
  - ca-certificates
  - vim
  - bash-completion
  - wget
  - iotop
  - sysstat
  - lsof
  - telnet
  - "{{ ( support_gluster_volume | bool ) | ternary('glusterfs-cli-7.4', 'vim') }}"
  - dstat
  - perf
  - blktrace
  - strace
  - iftop
  - mtr
  - traceroute
  - iptables
  - ethtool
  - net-tools
  - bind-utils
  - ipset
  - ipvsadm
  - iputils
  - net-tools
  - vim
  - bash-completion
  - wget
  - rsync
  - socat
  - ca-certificates

