## Change this to use another Kubernetes version, e.g. a current beta release
kube_version: v1.19.6

# Download ip
download_url: "http://1.2.3.4:3142"

# image registry config
image_registry_ip: "1.2.3.4"

image_registry_domain: "registry.domain"

image_registry_username: "admin"

image_registry_password: "PASSWORD"

# cluster VIP
cluster_vip: "1.2.3.4"

# image registry self-signed certificate
# default is true
image_registry_ca_self_sign: true

# Cluster name
cluster_identity_name: "kubernetes-stack"

# GPU enhancement, default is false
gpu_enhancement: "false"

# Set calico network backend: vxlan, bird(bgp),
# Default is vxlan.
calico_backend: "vxlan"

# If calico network backend is bgp, this field must be set.
# options: inCluster, router
# if peer type is inCluster, it will select k8s master as calico node;
# if peer type is router, it also needs to set switch IP;
# calico_peer_type: "inCluster"

# Set the switch IP, split by comma, like ["10.22.22.22", "10.23.23.23"]
# calico_peers: []

# Config ntp server ipaddress
#Example:
# ntp_server:
#   - 1.2.3.4
#   - 1.2.3.5
# ntp_server: []
